### ISSUE TITLE
PyNUTError: Socket error.

### ISSUE THREAD

**Issue by robmarkcole** [rshipp/python-nut2#1]
Hi how to troubleshoot` PyNUTError: Socket error.` I have checked the ip in `PyNUTClient init`

**Comment by rshipp** [comment]
It's just a generic network error https://docs.python.org/2/library/socket.html#socket.error

If you want more information you'll have to run the code in a debugger and inspect the exception, or edit the lib and add a print statement [here](https://github.com/rshipp/python-nut2/blob/master/nut2.py#L111) to see whats going on.
