### ISSUE TITLE
python 3.5

### ISSUE THREAD

**Issue by turboc1208** [rshipp/python-nut2#2]
Errors under Python3.5.3 when trying to run the example on the GIT README

Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nut2 import PyNUTClient
>>> client = PyNUTClient()
>>> client.help()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nut2.py", line 425, in help
    self._srv_handler.write("HELP\n")
  File "/usr/lib/python3.5/telnetlib.py", line 287, in write
    if IAC in buffer:
TypeError: 'in <string>' requires string as left operand, not bytes
>>> client.list_ups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nut2.py", line 133, in list_ups
    self._srv_handler.write("LIST UPS\n")
  File "/usr/lib/python3.5/telnetlib.py", line 287, in write
    if IAC in buffer:
TypeError: 'in <string>' requires string as left operand, not bytes
>>>

**Comment by rshipp** [comment]
Thanks for the issue! I don't have access to NUT+UPSs right now, but I think I have a solution for this anyway. I've published version 2.1.1 to PyPI, could you install it and let me know if it works for you?

**Comment by turboc1208** [comment]
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nut2 import PyNUTClient
>>> client = PyNUTClient
>>> client.help()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: help() missing 1 required positional argument: 'self'
>>> client.list_ups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list_ups() missing 1 required positional argument: 'self'

**Comment by rshipp** [comment]
Make sure you're using parentheses after the `PyNUTClient` to instantiate the object:

```python
client = PyNUTClient()
```

**Comment by turboc1208** [comment]
Duuuh.  LOL

Thanks

**Comment by rshipp** [comment]
Awesome, if that works I'll close this issue. Let me know if you run into anything else. :)

**Comment by turboc1208** [comment]
I’m writing a webapp service to feed data to home assistant.  Does the UPS send anytype of event that the API could respond to that tells when it a power outage of some type occurs rather than just polling it?

**Comment by rshipp** [comment]
I'm not sure, I know you can configure NUT to alert on certain things (going on battery, low battery, etc) and take actions on a server, but I don't know if that is just polling battery.status behind the scenes or what. You'll have better luck going through the [NUT docs](https://networkupstools.org/docs/user-manual.chunked/index.html) as I'm not that familiar with anything beyond polling the UPS variables - this seems relevant https://networkupstools.org/docs/user-manual.chunked/ar01s06.html#UPS_shutdown, but I don't know what those events it's mentioning are. Maybe you can figure something out with that?
